version: "1.0"
name: default
rules:
  # Deny rules first — these must match before broad allow rules
  - name: credential-files
    tools: [Read, Write, Edit]
    path_patterns:
      - "\\.env$|\\.env\\."
      - "\\.ssh/|\\.aws/"
      - "\\.key$|\\.pem$"
      - "id_rsa|credentials|secrets?"
    action: deny
    reason: "Credential/sensitive file access blocked"

  - name: no-force-push
    tool: Bash
    command_patterns: ["git\\s+push.*(-f|--force)"]
    action: deny
    reason: "Force push blocked"

  - name: destructive-bash
    tool: Bash
    command_patterns:
      - "rm\\s.*-.*r.*f|rm\\s+-rf"
      - "\\bsudo\\b"
      - "\\b(curl|wget)\\b.*\\|.*\\b(bash|sh|zsh)\\b"
      - "\\bchmod\\s+777\\b"
      - "\\b(DROP|TRUNCATE)\\s+(TABLE|DATABASE)\\b"
    action: deny
    reason: "Destructive or dangerous command"

  # Allow rules
  - name: agent-internal-tools
    tools: [AskUserQuestion, ExitPlanMode, Task, TaskCreate, TaskUpdate, TaskList, TaskGet, TodoWrite, EnterPlanMode]
    action: allow

  - name: read-only-tools
    tools: [Read, Glob, Grep, WebSearch, WebFetch, LS]
    action: allow

  - name: browser-readonly-tools
    tools:
      - browser_snapshot
      - browser_take_screenshot
      - browser_console_messages
      - browser_network_requests
      - browser_tab_list
      - browser_wait_for
      - browser_generate_playwright_test
    action: allow
    description: "Read-only browser observation"

  - name: read-only-bash
    tool: Bash
    command_patterns:
      - "^(ls|cat|head|tail|find|grep|wc|du|df|pwd|echo|date|whoami|which|type|file|stat)\\b"
      - "^git\\s+(-[a-zA-Z]\\s+\\S+\\s+|--[a-z-]+(=\\S+)?\\s+)*?(status|log|diff|show|branch|remote|tag)\\b"
    action: allow

  - name: plan-file-writes
    tools: [Write, Edit]
    path_patterns:
      - "\\.plan$"
      - "\\.claude/plans/"
    action: allow

  # Approval-required rules
  - name: git-mutations
    tool: Bash
    command_patterns:
      - "^git\\s+(-[a-zA-Z]\\s+\\S+\\s+|--[a-z-]+(=\\S+)?\\s+)*?(push|reset|rebase|merge|cherry-pick|rm)\\b"
    action: require_approval
    description: "Git mutation"

  - name: file-writes
    tools: [Write, Edit, NotebookEdit]
    action: require_approval
    description: "File modification"

  - name: network-bash
    tool: Bash
    command_patterns: ["^(curl|wget|ssh|scp|rsync)\\b"]
    action: require_approval
    description: "Network access"

  - name: browser-mutation-tools
    tools:
      - browser_navigate
      - browser_navigate_back
      - browser_navigate_forward
      - browser_click
      - browser_type
      - browser_hover
      - browser_drag
      - browser_press_key
      - browser_select_option
      - browser_file_upload
      - browser_handle_dialog
      - browser_fill_form
      - browser_evaluate
      - browser_tabs
      - browser_tab_new
      - browser_tab_select
      - browser_tab_close
      - browser_resize
      - browser_pdf_save
      - browser_close
      - browser_install
    action: require_approval
    description: "Browser interaction/mutation"

settings:
  default_action: require_approval
  approval_timeout_seconds: 300
